# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from DF/MsgRF.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class MsgRF(genpy.Message):
  _md5sum = "a0fc0b336c867cc76e65ffd4a8ba7649"
  _type = "DF/MsgRF"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
int32 axis_x
int32 axis_y
int32 axis_setMode
"""
  __slots__ = ['stamp','axis_x','axis_y','axis_setMode']
  _slot_types = ['time','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,axis_x,axis_y,axis_setMode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MsgRF, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.axis_x is None:
        self.axis_x = 0
      if self.axis_y is None:
        self.axis_y = 0
      if self.axis_setMode is None:
        self.axis_setMode = 0
    else:
      self.stamp = genpy.Time()
      self.axis_x = 0
      self.axis_y = 0
      self.axis_setMode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I3i().pack(_x.stamp.secs, _x.stamp.nsecs, _x.axis_x, _x.axis_y, _x.axis_setMode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.stamp.secs, _x.stamp.nsecs, _x.axis_x, _x.axis_y, _x.axis_setMode,) = _get_struct_2I3i().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I3i().pack(_x.stamp.secs, _x.stamp.nsecs, _x.axis_x, _x.axis_y, _x.axis_setMode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.stamp.secs, _x.stamp.nsecs, _x.axis_x, _x.axis_y, _x.axis_setMode,) = _get_struct_2I3i().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I3i = None
def _get_struct_2I3i():
    global _struct_2I3i
    if _struct_2I3i is None:
        _struct_2I3i = struct.Struct("<2I3i")
    return _struct_2I3i
