// Generated by gencpp from file DMF/MsgLine.msg
// DO NOT EDIT!


#ifndef DMF_MESSAGE_MSGLINE_H
#define DMF_MESSAGE_MSGLINE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace DMF
{
template <class ContainerAllocator>
struct MsgLine_
{
  typedef MsgLine_<ContainerAllocator> Type;

  MsgLine_()
    : num(0)  {
    }
  MsgLine_(const ContainerAllocator& _alloc)
    : num(0)  {
  (void)_alloc;
    }



   typedef int32_t _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::DMF::MsgLine_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::DMF::MsgLine_<ContainerAllocator> const> ConstPtr;

}; // struct MsgLine_

typedef ::DMF::MsgLine_<std::allocator<void> > MsgLine;

typedef boost::shared_ptr< ::DMF::MsgLine > MsgLinePtr;
typedef boost::shared_ptr< ::DMF::MsgLine const> MsgLineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::DMF::MsgLine_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::DMF::MsgLine_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::DMF::MsgLine_<ContainerAllocator1> & lhs, const ::DMF::MsgLine_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::DMF::MsgLine_<ContainerAllocator1> & lhs, const ::DMF::MsgLine_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace DMF

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::DMF::MsgLine_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::DMF::MsgLine_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DMF::MsgLine_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DMF::MsgLine_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DMF::MsgLine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DMF::MsgLine_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::DMF::MsgLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54b3c80efd6fae6e6ffff8a4b9facd69";
  }

  static const char* value(const ::DMF::MsgLine_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54b3c80efd6fae6eULL;
  static const uint64_t static_value2 = 0x6ffff8a4b9facd69ULL;
};

template<class ContainerAllocator>
struct DataType< ::DMF::MsgLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "DMF/MsgLine";
  }

  static const char* value(const ::DMF::MsgLine_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::DMF::MsgLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 num\n"
;
  }

  static const char* value(const ::DMF::MsgLine_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::DMF::MsgLine_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgLine_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::DMF::MsgLine_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::DMF::MsgLine_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DMF_MESSAGE_MSGLINE_H
