// Generated by gencpp from file DMF/MsgnCurLane.msg
// DO NOT EDIT!


#ifndef DMF_MESSAGE_MSGNCURLANE_H
#define DMF_MESSAGE_MSGNCURLANE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace DMF
{
template <class ContainerAllocator>
struct MsgnCurLane_
{
  typedef MsgnCurLane_<ContainerAllocator> Type;

  MsgnCurLane_()
    : nCurLane(0)  {
    }
  MsgnCurLane_(const ContainerAllocator& _alloc)
    : nCurLane(0)  {
  (void)_alloc;
    }



   typedef int32_t _nCurLane_type;
  _nCurLane_type nCurLane;





  typedef boost::shared_ptr< ::DMF::MsgnCurLane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::DMF::MsgnCurLane_<ContainerAllocator> const> ConstPtr;

}; // struct MsgnCurLane_

typedef ::DMF::MsgnCurLane_<std::allocator<void> > MsgnCurLane;

typedef boost::shared_ptr< ::DMF::MsgnCurLane > MsgnCurLanePtr;
typedef boost::shared_ptr< ::DMF::MsgnCurLane const> MsgnCurLaneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::DMF::MsgnCurLane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::DMF::MsgnCurLane_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::DMF::MsgnCurLane_<ContainerAllocator1> & lhs, const ::DMF::MsgnCurLane_<ContainerAllocator2> & rhs)
{
  return lhs.nCurLane == rhs.nCurLane;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::DMF::MsgnCurLane_<ContainerAllocator1> & lhs, const ::DMF::MsgnCurLane_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace DMF

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::DMF::MsgnCurLane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::DMF::MsgnCurLane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DMF::MsgnCurLane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DMF::MsgnCurLane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DMF::MsgnCurLane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DMF::MsgnCurLane_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::DMF::MsgnCurLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbea93705dcaf6e7297bfe685098a446";
  }

  static const char* value(const ::DMF::MsgnCurLane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdbea93705dcaf6e7ULL;
  static const uint64_t static_value2 = 0x297bfe685098a446ULL;
};

template<class ContainerAllocator>
struct DataType< ::DMF::MsgnCurLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "DMF/MsgnCurLane";
  }

  static const char* value(const ::DMF::MsgnCurLane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::DMF::MsgnCurLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 nCurLane\n"
;
  }

  static const char* value(const ::DMF::MsgnCurLane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::DMF::MsgnCurLane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nCurLane);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgnCurLane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::DMF::MsgnCurLane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::DMF::MsgnCurLane_<ContainerAllocator>& v)
  {
    s << indent << "nCurLane: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nCurLane);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DMF_MESSAGE_MSGNCURLANE_H
