// Generated by gencpp from file DMF/Speed.msg
// DO NOT EDIT!


#ifndef DMF_MESSAGE_SPEED_H
#define DMF_MESSAGE_SPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace DMF
{
template <class ContainerAllocator>
struct Speed_
{
  typedef Speed_<ContainerAllocator> Type;

  Speed_()
    : speed(0)
    , detect(0)  {
    }
  Speed_(const ContainerAllocator& _alloc)
    : speed(0)
    , detect(0)  {
  (void)_alloc;
    }



   typedef int32_t _speed_type;
  _speed_type speed;

   typedef int32_t _detect_type;
  _detect_type detect;





  typedef boost::shared_ptr< ::DMF::Speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::DMF::Speed_<ContainerAllocator> const> ConstPtr;

}; // struct Speed_

typedef ::DMF::Speed_<std::allocator<void> > Speed;

typedef boost::shared_ptr< ::DMF::Speed > SpeedPtr;
typedef boost::shared_ptr< ::DMF::Speed const> SpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::DMF::Speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::DMF::Speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::DMF::Speed_<ContainerAllocator1> & lhs, const ::DMF::Speed_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.detect == rhs.detect;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::DMF::Speed_<ContainerAllocator1> & lhs, const ::DMF::Speed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace DMF

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::DMF::Speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::DMF::Speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DMF::Speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DMF::Speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DMF::Speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DMF::Speed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::DMF::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8a40abb3e4c019d7e3a9e9a3dddd6b9";
  }

  static const char* value(const ::DMF::Speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8a40abb3e4c019dULL;
  static const uint64_t static_value2 = 0x7e3a9e9a3dddd6b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::DMF::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "DMF/Speed";
  }

  static const char* value(const ::DMF::Speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::DMF::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 speed\n"
"int32 detect\n"
;
  }

  static const char* value(const ::DMF::Speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::DMF::Speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.detect);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::DMF::Speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::DMF::Speed_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed);
    s << indent << "detect: ";
    Printer<int32_t>::stream(s, indent + "  ", v.detect);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DMF_MESSAGE_SPEED_H
